### ISSUE TITLE
Resharper DPA Complaint for DataTypes.ReadNextVarInt(Queue)

### ISSUE THREAD

**Issue by breadbyte** [breadbyte/Minecraft-Console-Client#3]
# DataTypes.ReadNextVarInt(Queue)

#### 1,747.8 MB LOH String Allocation
```
at String.Create(int, , SpanAction)
at BitConverter.ToString(byte[], int, int)
at BitConverter.ToString(byte[])
at DataTypes.ReadNextVarInt(Queue) in C:\pubproj\Minecraft-Console-Client\MinecraftClient\Protocol\Handlers\DataTypes.cs:line 256 column 13
at Protocol18Terrain.ProcessChunkColumnData(int, int, ushort, ushort, bool, bool, int, Queue) in C:\pubproj\Minecraft-Console-Client\MinecraftClient\Protocol\Handlers\Protocol18Terrain.cs:line 71 column 29
at Protocol18Handler+<>c__DisplayClass39_1.<HandlePacket>b__1() in C:\pubproj\Minecraft-Console-Client\MinecraftClient\Protocol\Handlers\Protocol18.cs:line 459 column 37
at Task.InnerInvoke()
at Task+<>c.<.cctor>b__277_0(Object)
at ExecutionContext.RunFromThreadPoolDispatchLoop(Thread, ExecutionContext, ContextCallback, Object)
at Task.ExecuteWithThreadLocal(ref Task, Thread)
at Task.ExecuteEntryUnsafe(Thread)
at Task.ExecuteFromThreadPool(Thread)
at ThreadPoolWorkQueue.Dispatch()
at _ThreadPoolWaitCallback.PerformWaitCallback()
```
#### 467.9 MB SOH String Allocation
```
at String.Create(int, , SpanAction)
at BitConverter.ToString(byte[], int, int)
at BitConverter.ToString(byte[])
at DataTypes.ReadNextVarInt(Queue) in C:\pubproj\Minecraft-Console-Client\MinecraftClient\Protocol\Handlers\DataTypes.cs:line 256 column 13
at Protocol18Terrain.ProcessChunkColumnData(int, int, ushort, ushort, bool, bool, int, Queue) in C:\pubproj\Minecraft-Console-Client\MinecraftClient\Protocol\Handlers\Protocol18Terrain.cs:line 71 column 29
at Protocol18Handler+<>c__DisplayClass39_1.<HandlePacket>b__1() in C:\pubproj\Minecraft-Console-Client\MinecraftClient\Protocol\Handlers\Protocol18.cs:line 459 column 37
at Task.InnerInvoke()
at Task+<>c.<.cctor>b__277_0(Object)
at ExecutionContext.RunFromThreadPoolDispatchLoop(Thread, ExecutionContext, ContextCallback, Object)
at Task.ExecuteWithThreadLocal(ref Task, Thread)
at Task.ExecuteEntryUnsafe(Thread)
at Task.ExecuteFromThreadPool(Thread)
at ThreadPoolWorkQueue.Dispatch()
at _ThreadPoolWaitCallback.PerformWaitCallback()
```

#### 395.7 MB SOH Byte[] Allocation
```
at Queue<Byte>.ToArray()
at DataTypes.ReadNextVarInt(Queue) in C:\pubproj\Minecraft-Console-Client\MinecraftClient\Protocol\Handlers\DataTypes.cs:line 256 column 13
at Protocol18Terrain.ProcessChunkColumnData(int, int, ushort, ushort, bool, bool, int, Queue) in C:\pubproj\Minecraft-Console-Client\MinecraftClient\Protocol\Handlers\Protocol18Terrain.cs:line 71 column 29
at Protocol18Handler+<>c__DisplayClass39_1.<HandlePacket>b__1() in C:\pubproj\Minecraft-Console-Client\MinecraftClient\Protocol\Handlers\Protocol18.cs:line 459 column 37
at Task.InnerInvoke()
at Task+<>c.<.cctor>b__277_0(Object)
at ExecutionContext.RunFromThreadPoolDispatchLoop(Thread, ExecutionContext, ContextCallback, Object)
at Task.ExecuteWithThreadLocal(ref Task, Thread)
at Task.ExecuteEntryUnsafe(Thread)
at Task.ExecuteFromThreadPool(Thread)
at ThreadPoolWorkQueue.Dispatch()
at _ThreadPoolWaitCallback.PerformWaitCallback()
```

#### 167.3 MB LOH String Allocation
```
at String.Create(int, , SpanAction)
at BitConverter.ToString(byte[], int, int)
at BitConverter.ToString(byte[])
at DataTypes.ReadNextVarInt(Queue) in C:\pubproj\Minecraft-Console-Client\MinecraftClient\Protocol\Handlers\DataTypes.cs:line 256 column 13
at Protocol18Terrain.ProcessChunkColumnData(int, int, ushort, ushort, bool, bool, int, Queue) in C:\pubproj\Minecraft-Console-Client\MinecraftClient\Protocol\Handlers\Protocol18Terrain.cs:line 66 column 29
at Protocol18Handler+<>c__DisplayClass39_1.<HandlePacket>b__1() in C:\pubproj\Minecraft-Console-Client\MinecraftClient\Protocol\Handlers\Protocol18.cs:line 459 column 37
at Task.InnerInvoke()
at Task+<>c.<.cctor>b__277_0(Object)
at ExecutionContext.RunFromThreadPoolDispatchLoop(Thread, ExecutionContext, ContextCallback, Object)
at Task.ExecuteWithThreadLocal(ref Task, Thread)
at Task.ExecuteEntryUnsafe(Thread)
at Task.ExecuteFromThreadPool(Thread)
at ThreadPoolWorkQueue.Dispatch()
at _ThreadPoolWaitCallback.PerformWaitCallback()
```

#### 137.2 MB LOH String Allocation
```
at String.Create(int, , SpanAction)
at BitConverter.ToString(byte[], int, int)
at BitConverter.ToString(byte[])
at DataTypes.ReadNextVarInt(Queue) in C:\pubproj\Minecraft-Console-Client\MinecraftClient\Protocol\Handlers\DataTypes.cs:line 256 column 13
at DataTypes.ReadNextULongArray(Queue) in C:\pubproj\Minecraft-Console-Client\MinecraftClient\Protocol\Handlers\DataTypes.cs:line 201 column 13
at Protocol18Terrain.ProcessChunkColumnData(int, int, ushort, ushort, bool, bool, int, Queue) in C:\pubproj\Minecraft-Console-Client\MinecraftClient\Protocol\Handlers\Protocol18Terrain.cs:line 79 column 25
at Protocol18Handler+<>c__DisplayClass39_1.<HandlePacket>b__1() in C:\pubproj\Minecraft-Console-Client\MinecraftClient\Protocol\Handlers\Protocol18.cs:line 459 column 37
at Task.InnerInvoke()
at Task+<>c.<.cctor>b__277_0(Object)
at ExecutionContext.RunFromThreadPoolDispatchLoop(Thread, ExecutionContext, ContextCallback, Object)
at Task.ExecuteWithThreadLocal(ref Task, Thread)
at Task.ExecuteEntryUnsafe(Thread)
at Task.ExecuteFromThreadPool(Thread)
at ThreadPoolWorkQueue.Dispatch()
at _ThreadPoolWaitCallback.PerformWaitCallback()
```

#### 66.7 MB LOH String Allocation
```
at String.Create(int, , SpanAction)
at BitConverter.ToString(byte[], int, int)
at BitConverter.ToString(byte[])
at DataTypes.ReadNextVarInt(Queue) in C:\pubproj\Minecraft-Console-Client\MinecraftClient\Protocol\Handlers\DataTypes.cs:line 256 column 13
at Protocol18Handler.HandlePacket(int, Queue) in C:\pubproj\Minecraft-Console-Client\MinecraftClient\Protocol\Handlers\Protocol18.cs:line 457 column 33
at Protocol18Handler.Update() in C:\pubproj\Minecraft-Console-Client\MinecraftClient\Protocol\Handlers\Protocol18.cs:line 195 column 21
at Protocol18Handler.Updater(Object) in C:\pubproj\Minecraft-Console-Client\MinecraftClient\Protocol\Handlers\Protocol18.cs:line 161 column 21
at ThreadHelper.ThreadStart_Context(Object)
at ExecutionContext.RunInternal(ExecutionContext, ContextCallback, Object)
at ThreadHelper.ThreadStart(Object)
```

#### 66.6 MB LOH String Allocation
```
at String.Create(int, , SpanAction)
at BitConverter.ToString(byte[], int, int)
at BitConverter.ToString(byte[])
at DataTypes.ReadNextVarInt(Queue) in C:\pubproj\Minecraft-Console-Client\MinecraftClient\Protocol\Handlers\DataTypes.cs:line 256 column 13
at Protocol18Handler.ReadNextPacket(ref int, Queue) in C:\pubproj\Minecraft-Console-Client\MinecraftClient\Protocol\Handlers\Protocol18.cs:line 233 column 13
at Protocol18Handler.Update() in C:\pubproj\Minecraft-Console-Client\MinecraftClient\Protocol\Handlers\Protocol18.cs:line 194 column 21
at Protocol18Handler.Updater(Object) in C:\pubproj\Minecraft-Console-Client\MinecraftClient\Protocol\Handlers\Protocol18.cs:line 161 column 21
at ThreadHelper.ThreadStart_Context(Object)
at ExecutionContext.RunInternal(ExecutionContext, ContextCallback, Object)
at ThreadHelper.ThreadStart(Object)
```

#### 65.4 MB LOH String Allocation
```
at String.Create(int, , SpanAction)
at BitConverter.ToString(byte[], int, int)
at BitConverter.ToString(byte[])
at DataTypes.ReadNextVarInt(Queue) in C:\pubproj\Minecraft-Console-Client\MinecraftClient\Protocol\Handlers\DataTypes.cs:line 256 column 13
at Protocol18Handler.HandlePacket(int, Queue) in C:\pubproj\Minecraft-Console-Client\MinecraftClient\Protocol\Handlers\Protocol18.cs:line 423 column 29
at Protocol18Handler.Update() in C:\pubproj\Minecraft-Console-Client\MinecraftClient\Protocol\Handlers\Protocol18.cs:line 195 column 21
at Protocol18Handler.Updater(Object) in C:\pubproj\Minecraft-Console-Client\MinecraftClient\Protocol\Handlers\Protocol18.cs:line 161 column 21
at ThreadHelper.ThreadStart_Context(Object)
at ExecutionContext.RunInternal(ExecutionContext, ContextCallback, Object)
at ThreadHelper.ThreadStart(Object)
```

**Comment by breadbyte** [comment]
Most of these issues are in the Terrain Handler and `HandlePacket`. 
We can always recreate these errors when looking for things to optimize/fix.
